### ISSUE TITLE
Sim won't behave properly after keyboard nav in full screen IE

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#317]
Device
hp laptop
OS
Win 7
Browser
Internet explorer.
Problem Description
For https://github.com/phetsims/QA/issues/200 possibly related to https://github.com/phetsims/john-travoltage/issues/314
When using keyboard nav in the full screen mode, if you switch to using a mouse the sim will become uninteractable.  Any animations in progress (electron discharge) will continue, but mouse input will do nothing.  Leaving full screen does not solve this.  It seems the only way to leave is by pressing escape, as using keyboard nav does not seem to work.  After escaping, if mouse was used in full screen the sim is still uninteractable with mouse.  If it was not, and keyboard nav was used in an attempt to leave, the phet menu stays up, even when the sim is being manipulated.
Steps to Reproduce
1. Go to the full screen
2. Use keyboard nav to manipulate the sim
3. Click something with the mouse and note how the sim responds
4. Press escape to leave
5. Hit refresh
6. Repeate 1 and 2
7. Use keyboard nav to try and leave full screen.  Nothing happens
8. Press escape to leave
9. Note phet menu behavior

**Comment by jessegreenberg** [comment]
@KatieWoe is this reproducible in Windows 10?

**Comment by KatieWoe** [comment]
@jessegreenberg yes

**Comment by jessegreenberg** [comment]
Good deal, that will make it easier to investigate. Thanks.

**Comment by jessegreenberg** [comment]
Able to reproduce, shortly after the bug happened, IE11 crashed with "A problem occurred..." I verified that this is specific to IE11, and doesn't happen in Chrome or Edge.

**Comment by jessegreenberg** [comment]
When I run a mangle=false version of the sim, IE11 tells me
`SCRIPT16389: Incorrect function.`

Pointing to this line
```js
            blur: function() {
                this._primarySibling.blur();
            },
```

**Comment by jessegreenberg** [comment]
Presumably this is in AccessiblePeer.

**Comment by KatieWoe** [comment]
Noting here that this is present on Win 8.1 IE as well

**Comment by jessegreenberg** [comment]
The HTML element that we are trying to blur is defined in IE11.

**Comment by jessegreenberg** [comment]
![capture](https://user-images.githubusercontent.com/6396244/46501270-fc144500-c7f2-11e8-944b-a904431acc3f.PNG)

I am pretty sure that what is happening is that blur() in IE11 throws an error if the element is not in the document.

**Comment by jessegreenberg** [comment]
Here are some modifications in a non-mangled built version:
```js
blur: function() {
  window.peer = this, window.element = this._primarySibling, document.activeElement === this._primarySibling && this._primarySibling.blur();
},
```
 * window.element.blur() works just fine.
 * window.peer._primarySibling.blur() works just fine.
 * this._primarySibling.blur() is throwing an error "Incorrect Function".
 * I verified that window.peer._primarySibling === document.activeElement.

So it seems like things are OK in the console, but not OK at runtime.

**Comment by jessegreenberg** [comment]
This bug report looks really similar to what we are seeing
https://bugs.jquery.com/ticket/15044

**Comment by jessegreenberg** [comment]
Maybe the blur is a read herring, and the error is happening elsewhere.

**Comment by jessegreenberg** [comment]
Some output in the console, but I still am very unclear on what is happening here
![capture](https://user-images.githubusercontent.com/6396244/46507001-62559380-c804-11e8-80ba-ab9daed7a7b1.PNG)

**Comment by jessegreenberg** [comment]
This isn't happening in the deployed version of the sim, that might help isolate the problem.

**Comment by KatieWoe** [comment]
Just found that this issue is happening to an even larger extent in https://github.com/phetsims/QA/issues/203 (Coulomb's Law).  In addition to this issue, if keyboard nav is used on the home screen on full screen it crashes and looses many images.
![odd](https://user-images.githubusercontent.com/41024075/46507413-96758800-c7f5-11e8-8a47-4c68ebadfba9.PNG)

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, that is the same issue. We are trying to blur document.activeElement in fullScreen mode and IE11 reports "Incorrect Function".

**Comment by jessegreenberg** [comment]
So it seems like blur works as long as the element is not document.activeElement for IE11 in fullscreen mode...which means that blur doesn't work for IE11 in fullscreen mode. But this implementation of AccessiblePeer.blur makes the problem go away in both john-travoltage and coulombs-law:
```js
    blur: function() {
      assert && assert( this._primarySibling, 'must have a primary sibling to blur' );

      var tempElement = document.createElement( 'button' );
      tempElement.focus();
      // this._primarySibling.blur();
    },
```

**Comment by jessegreenberg** [comment]
A bug reported to jquery about this in https://bugs.jquery.com/ticket/15044 was closed with comment
> This bug is esoteric enough that I will leave it for Microsoft. If it isn't fixed soon and becomes a commonly reported issue we could investigate a workaround.

But the sim becomes unusable in this case so Ill continue with https://github.com/phetsims/john-travoltage/issues/317#issuecomment-427198363 as a workaround.

**Comment by jessegreenberg** [comment]
It did not work. https://github.com/phetsims/john-travoltage/issues/317#issuecomment-427403989 is a more graceful solution, and is definitely one way to go. Apparently IE11 has a special function `setActive`, maybe that will work better? http://help.dottoro.com/ljqmdirr.php

**Comment by jessegreenberg** [comment]
It did not. Comments in other threads are suggesting a timeout might work as a workaround.

**Comment by jessegreenberg** [comment]
@zepumph helped me commit this change, we verified that this is working now in IE11 and in other platforms too. The release of JT will need a scenery branch with this commit.

**Comment by jessegreenberg** [comment]
The above commit should fix all occurrences of this (JT, CL, GFL:B, and more). @KatieWoe can you please check that this is fixed in built versions of the sim in IE11 using phettest (since requirejs won't work in IE11)?

**Comment by KatieWoe** [comment]
@jessegreenberg just test the three sims mentioned on Win 10 IE 11 and it all looks good.

**Comment by jbphet** [comment]
This isn't working for me.  I first tried propagating it to the RC branch, but the problem wasn't gone, so I tried building off master, and I'm still seeing the lockup there as well.  I noticed the code is using `this` in a closure, which looks suspicious.  Are you sure this is fixed?

**Comment by jessegreenberg** [comment]
Sorry @jbphet, that looks very wrong. It is very weird that IE11 *isn't* breaking when @KatieWoe or I test it. I just tested it again off of master and behavior seems ok.

**Comment by jessegreenberg** [comment]
I changed it to use `self`, but now that the reference to the AccessiblePeer is correct, the reference to _primarySibling is gone after the menu has been hidden, so `self._primarySibling.blur();` is throwing an error for me now. I will have to follow up tomorrow.

**Comment by jessegreenberg** [comment]
Worked with @jbphet to verify a fix. Removing my assignment for now.

**Comment by KatieWoe** [comment]
@jessegreenberg Looks ok on JT 1.5.0-rc.3 on Win 10 IE 11.  Do you want this left open for a future maintenance release, or should it be closed?
