### ISSUE TITLE
Try to improve foot dragging sound

### ISSUE THREAD

**Issue by jbphet** [phetsims/john-travoltage#329]
In the 2/26/2019 sound design meeting, @emily-phet requested that some time be taken to see if we can make some improvements to the sound that is produced when JT's foot is moved back and forth.  I agree that this can be improved.  Our general thoughts on this sound is that it gets the point across reasonably well, but seems a little harsh and artificial.  I'll see if I can make some refinements that make it something we can be happier with.

**Comment by jbphet** [comment]
Once I've made some changes, @Ashton-Morris and I will refine and potentially more some more refinements, and then we will plan to review in the 3/19/2019 sound design meeting.

**Comment by jbphet** [comment]
For reference, the improvements are being made relative to the currently published version, which is v1.5.2.  [This link](https://phet-dev.colorado.edu/html/john-travoltage/1.5.2/phet/john-travoltage_en_phet.html) to that version should be reasonably enduring.

**Comment by jbphet** [comment]
In looking at the currently live version, it's behavior is better than that of the current master version.  The file `FootDragSoundGenerator.js` hasn't changed, so the problem is likely due to changes in the parent `NoiseGenerator` type.  The first order of business should be to fix this up.

**Comment by jbphet** [comment]
On master, I've fixed two issues that were not on the published version.  These resulted from changes to the `NoiseGenerator` type.

+ drag sound continued above the carpet
+ drag sound was "jittery", meaning that the volume changed frequently in audible ways

Once these were fixed, I made the following changes that should affect the way the master version sounds with respect to the published version:
+ changed the noise source type to `brown`
+ lowered the center frequency for the noise source a little bit
+ reduced the front-to-back frequency delta
+ reduced the time for the sound to start playing

I'll review these shortly and we will decide where to go next.

**Comment by jbphet** [comment]
I've published a version with the changes described in the preceding comment, plus a modification to the overall volume that was done after reviewing with @Ashton-Morris.  The link is below.  Overall, I find this change to be much less "in your face", so I think it's an improvement.

@emily-phet and @Ashton-Morris - please review and provide your input.

@Ashton-Morris said during his and my meeting on 3/15/2019 that some of the transitions between the forward and backward directions of foot motion were a bit abrupt and he was hearing audible clicks.  I'm not noticing this much, so it could have been a Zoom issue or it could just be that the frequency content is high enough that I can't hear it.  Please check for this as part of your review.  

https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-dev.1/phet/john-travoltage_en_phet.html

**Comment by emily-phet** [comment]
@jbphet 
When rubbing the foot slow, this sounds much more pleasant than the current published version! When rubbing fast, it sounds 'clippy' - less smooth than when rubbing fast with the current published version. (Using Safari with headphones)

**Comment by Ashton-Morris** [comment]
I am also still getting the clicks when dragging the foot. So its an outside of Zoom issue.

**Comment by jbphet** [comment]
This problem was particularly bad in Safari because of differences in the way that it implement gain changes.  I've logged an issue with the W3C Web Audio group, and have changed the PhET audio library to use a different gain change approach.  This seems to work better, but may bring back some of the issues that we were seeing before related to hearing sounds at initialization.

At any rate, a new version is available at  https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-dev.2/phet/john-travoltage_en_phet.html.  @emily-phet and @Ashton-Morris - please review and provide feedback (we can also discuss, review, and tweak during tomorrow's weekly sound design meeting).

**Comment by jbphet** [comment]
We reviewed the latest changes during the 4/9/2019 Sound Design meeting, and the conclusion was that it is better - the clicking is gone and the sound isn't as harsh - but it could still use some improvement.  Since this sound will be used in other places, such as the balloon-rubbing-on-sweater sound for Balloons and Static Electricity, it's worth investing a bit more time in improving this.  

Based on what we discussed, I'll try making the volume and pitch change smoothly with the velocity of the leg, and will add some constants that will allow use to do some test-and-refine steps at the next meeting.

**Comment by jbphet** [comment]
We (@emily-phet, @Ashton-Morris, and I) reviewed the latest changes on master at the 4/16/2019 sound design meeting and concluded that it is definitely an improvement over the current live versions.  Next steps are:

+ Fix the time constant that is used when starting the sound
+ Check in with @jessegreenberg and see if there is an upcoming maintenance release that this can go into

**Comment by jbphet** [comment]
@jessegreenberg - we are trying to decide whether to do a maintenance release to get these changes published, and someone thought you might be planning a release of this sim for other reasons.  Any truth to that rumor?  If so, were you planning to publish off of master or the current release branch?

**Comment by jessegreenberg** [comment]
I am not aware of any other plans to republish this sim now @jbphet.

**Comment by jbphet** [comment]
In the 6/4/2019 sound design meeting, we discussed whether it was worth the time to do a maintenance release of this sim to get the improved foot dragging sounds published.  @emily-phet recommented that we wait, since we may well do a maintenance release or a release from master when we’re doing some work on this related to the haptics effort.  I will mark as deferred and add other appropriate labels.

**Comment by jbphet** [comment]
Note to self or whoever does the next publication: I don't think the changes were moved to the release branch yet, so that would be part of the process of publishing a maintenance release.

**Comment by jessegreenberg** [comment]
This sim was republished off of master this quarter and includes these changes. @jbphet OK to close this issue?

**Comment by jbphet** [comment]
Yes, thanks for letting me know.  Closing.
